### ISSUE TITLE
Handlers hang forever

### ISSUE THREAD

**Issue by wbrickner** [Restioson/xtra#46] opened 2021-10-26 22:47 UTC
Hello,

I have run into an issue in `xtra` (via `spaad`).
It may be my fault, but it's not clear to me.

- I define a `Agent` actor, and make a public `lazy_static!` of it
- I define `Config` actor, and make a public `lazy_static!` of it

This way anywhere in the application I can just send a message to the actors, it's great.
This may be the reason for my issue, idk.

So for example, in the `new()` of `Agent`:

```rust
#[spaad::entangled]
pub struct Agent {
  my_state: HashMap<String, ConfigValue>
}

#[spaad::entangled]
impl Actor for Agent {}

#[spaad::entangled]
impl Agent {
  #[spaad::spawn]
  pub fn new() -> Self {
    let c = futures::executor::block_on(CONFIG.get_config_value());
    log::debug!("Got config: {:#?}", c);

    Self {
      // use config values to make my_state
      my_state: {  } // ...
    }
  }
  // ...
}
```

where `get_config_value` in this example is a handler.
We never reach `Got config: ...`, shockingly we also never reach the inside of `get_config_value`.

This is a contrived example, I had the same issue occur before where I was sending messages to the `AGENT` `lazy_static!` from a tokio task created with `spawn`.  I spent like a day trying to fix it, and then it began working, but I could not figure out exactly what made it work.  I'm pretty sure I'm missing some big piece of information.

`AGENT` can handle messages sent to it, however `CONFIG` never can.  They seem to be identical in implementation and instantiation.  `CONFIG` succeeds in being created, so it's not like its waiting for the actor to come alive.

Any help would be great, thank you.

**Comment by wbrickner** [comment] 2021-10-31 00:55
Unfortunately the system is proprietary, which is why I have been a bit cagey / have been posting example-like code here, so I can't share the actual source with you. Suffice to say, I wanted help, so I made sure the structure and any important details were mirrored.  Looks like there's something about my system that either creates / teases out this bug that is not present in my example code.

I have had to move on. I realized that my use case could replace all uses of `xtra` with a bunch of `tokio::sync::Mutex`,
and it has resolved all the hanging issues.

- So, `block_on` is not the issue, even doing `CONFIG.get_my_config().await` also fails inside the `async fn started` life cycle method.  
- Recall that it is not the initialization of CONFIG either, initialization occurs long before and the handlers work in other places, but as soon as `Agent` is initialized, the handlers hang indefinitely.
- The method handler I declare does not even get called, the deadlock (if that is the root cause) occurs as soon as I call `.await`, but before the method actually executes any code. 

I agree, I don't think it is an issue with unsafe or memory crimes, it is instead probably a concurrency unsoundness thing like you mention.

Everything points to mystery, my bet is that there is a flaw in the code generation in `spaad`.

**Comment by Restioson** [comment] 2021-10-31 09:47
Expanding the example that you sent yields the following for the inner `new` method:

```rust
    #[allow(unused_imports)]
    use __ActorAActor::ActorA;
    impl __ActorAActor::ActorA {
        pub fn new() -> Self {
            let info = block_on(ACTOR_B.get_info());
            {
                ::std::io::_print(::core::fmt::Arguments::new_v1(
                    &["Got info: ", "\n"],
                    &match (&info,) {
                        (arg0,) => [::core::fmt::ArgumentV1::new(
                            arg0,
                            ::core::fmt::Display::fmt,
                        )],
                    },
                ));
            };
            Self { info }
        }
    // ...
}
```

So, this is exactly what you wrote.

And this is the wrapping `new` method as generated:

```rust
impl ActorA {
    pub fn new<ActorSpawner: ::spaad::export::xtra::spawn::Spawner>(
        actor_spawner: &mut ActorSpawner,
    ) -> Self {
        use ::spaad::export::xtra::prelude::*;
        let act = __ActorAActor::ActorA::new();
        let addr = act.create(::std::option::Option::None).spawn(actor_spawner);
        ActorA { addr }
    }
    // ...
}
```

If what you're saying is indeed true (that it hangs on the call to ACTOR_B.get_info()), I do not see any way how spaad codegen could have caused this, or indeed xtra code. This seems to be completely down to the specifics of the new method and potential interdependencies between ActorA and ActorB. 

Here is [the rest of the generated code](https://gist.github.com/Restioson/d466c83ec3229baa74c86951da103926).

**Comment by Restioson** [comment] 2022-01-21 08:29
Closing as unable to reproduce.

**Closed by Restioson** 2022-01-21 08:29 UTC
Labels: bug, waiting on submitter
